name: Preview Build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            os_name: windows
            arch: amd64
          - os: windows-latest
            os_name: windows
            arch: arm64
          - os: macos-13
            os_name: darwin
            arch: amd64
            target_arch: x86_64
          - os: macos-latest
            os_name: darwin
            arch: arm64
            target_arch: arm64
          - os: ubuntu-latest
            os_name: linux
            arch: amd64
          - os: ubuntu-24.04-arm
            os_name: linux
            arch: arm64
            
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install uv and restore cache
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.20"
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"

    - name: Install Dependencies
      run: uv sync

    # Download ZJU-connect core package
    - name: Download ZJU-connect Core
      run: |
        mkdir -p app/core
        curl -L "https://github.com/Mythologyli/zju-connect/releases/download/v0.9.0/zju-connect-${{ matrix.os_name }}-${{ matrix.arch }}.zip" -o app/core/zju-connect.zip
        if [ "${{ matrix.os_name }}" = "windows" ]; then
          powershell -command "Expand-Archive -Path app/core/zju-connect.zip -DestinationPath app/core"
        else
          unzip -o app/core/zju-connect.zip -d app/core
        fi
        rm app/core/zju-connect.zip
      shell: bash
    
    # macOS specific build
    - name: Build Executable (macOS)
      if: runner.os == 'macOS'
      run: |
        source .venv/bin/activate
        pyside6-rcc app/resources/resources.qrc -o app/common/resources.py

        python -m nuitka \
          --standalone \
          --assume-yes-for-downloads \
          --enable-plugin=pyside6 \
          --include-data-dir=app=app \
          --include-data-files=.app-version=.app-version \
          --macos-target-arch=${{ matrix.target_arch }} \
          --macos-create-app-bundle \
          --macos-app-icon=app/resources/icons/icon.icns \
          --macos-app-name="HITSZ Connect Verge Preview" \
          --macos-app-version=$(cat .app-version) \
          --output-dir=dist \
          --remove-output \
          app/main.py

        mv dist/main.app dist/HITSZ\ Connect\ Verge\ Preview.app

    - name: Create DMG (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install create-dmg
        create-dmg \
          --volname "HITSZ Connect Verge Preview" \
          --background "app/resources/installer/bg.svg" \
          --window-pos 400 200 \
          --window-size 660 400 \
          --icon-size 100 \
          --icon "HITSZ Connect Verge Preview.app" 160 185 \
          --app-drop-link 500 185 \
          "dist/hitsz-connect-verge-preview-${{ matrix.os_name }}-${{ matrix.arch }}.dmg" \
          "dist/HITSZ Connect Verge Preview.app"

    # Windows specific build        
    - name: Build Executable (Windows)
      if: runner.os == 'Windows'
      run: |
        .\.venv\Scripts\Activate.ps1
        pyside6-rcc .\app\resources\resources.qrc -o .\app\common\resources.py
        
        python -m nuitka `
          --standalone `
          --assume-yes-for-downloads `
          --enable-plugin=pyside6 `
          --include-data-dir=app=app `
          --include-data-files=app\core\zju-connect.exe=app\core\zju-connect.exe `
          --include-data-files=.app-version=.app-version `
          --product-name="HITSZ Connect Verge Preview" `
          --product-version=$(Get-Content .app-version) `
          --file-description="HITSZ Connect Verge Preview" `
          --windows-icon-from-ico=app\resources\icons\icon.ico `
          --windows-console-mode=disable `
          --output-dir=dist `
          --remove-output `
          app/main.py
        
    - name: Compile Installer (Windows)
      if: runner.os == 'Windows'
      run: |
        # Install Inno Setup
        choco install innosetup -y
        
        # Compile installer
        $version = Get-Content .app-version
        $setup_script = ".\setup.iss"
        iscc /DMyAppVersion="$version" `
             /DArchitecture="${{ matrix.arch }}" `
             $setup_script

    # Linux specific build
    - name: Cache apt packages
      if: runner.os == 'Linux'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libglib2.0-0 libgl1 dpkg-dev debhelper 
          libxcb-xinerama0 
          libxkbcommon-x11-0 
          libxcb-icccm4 
          libxcb-image0 
          libxcb-keysyms1 
          libxcb-randr0 
          libxcb-render-util0 
          libxcb-xfixes0 
          libxcb-shape0 
          libxcb-cursor0 
          libxcb-sync1 
          libxcb-xkb1 
          libxcb1
          patchelf
          build-essential
        version: 1.0
    
    - name: Build Executable (Linux)
      if: runner.os == 'Linux'
      run: |
        source .venv/bin/activate
        pyside6-rcc app/resources/resources.qrc -o app/common/resources.py
        
        python -m nuitka \
          --standalone \
          --assume-yes-for-downloads \
          --enable-plugin=pyside6 \
          --include-data-dir=app=app \
          --include-data-files=.app-version=.app-version \
          --product-name="HITSZ Connect Verge Preview" \
          --file-description="HITSZ Connect Verge Preview" \
          --linux-icon=app/resources/icons/icon.png \
          --output-dir=dist \
          --remove-output \
          app/main.py

          mv dist/main.dist dist/hitsz-connect-verge-preview
          mv dist/hitsz-connect-verge-preview/main.bin dist/hitsz-connect-verge-preview/hitsz-connect-verge-preview

    - name: Create DEB Package (Linux)
      if: runner.os == 'Linux'
      run: |
        VERSION=$(cat .app-version)
        mkdir -p deb/DEBIAN
        mkdir -p deb/usr/bin
        mkdir -p deb/usr/share/applications
        mkdir -p deb/usr/share/icons/hicolor/256x256/apps
        mkdir -p deb/usr/lib/hitsz-connect-verge-preview
        
        # Copy the entire distribution folder instead of just the binary
        cp -r dist/hitsz-connect-verge-preview/* deb/usr/lib/hitsz-connect-verge-preview/
        
        cat > deb/usr/bin/hitsz-connect-verge-preview << EOF
        #!/bin/bash
        export PYTHONPATH=/usr/lib/hitsz-connect-verge-preview
        export LD_LIBRARY_PATH=/usr/lib/hitsz-connect-verge-preview:\$LD_LIBRARY_PATH
        cd /usr/lib/hitsz-connect-verge-preview
        exec ./hitsz-connect-verge-preview "\$@"
        EOF
        
        chmod +x deb/usr/bin/hitsz-connect-verge-preview
        
        cp app/resources/icons/icon.png deb/usr/share/icons/hicolor/256x256/apps/hitsz-connect-verge-preview.png
        
        cat > deb/usr/share/applications/hitsz-connect-verge-preview.desktop << EOF
        [Desktop Entry]
        Name=HITSZ Connect Verge Preview
        Exec=hitsz-connect-verge-preview
        Icon=hitsz-connect-verge-preview
        Type=Application
        Categories=Network;
        EOF
        
        cat > deb/DEBIAN/control << EOF
        Package: hitsz-connect-verge-preview
        Version: $VERSION
        Section: net
        Priority: optional
        Architecture: ${{ matrix.arch == 'amd64' && 'amd64' || 'arm64' }}
        Maintainer: Kowyo
        Description: HITSZ Connect Verge Preview
         A preview version of VPN client for ZJU Connect/EasyConnect users.
        Depends: libc6, libglib2.0-0, libgl1
        EOF
        
        dpkg-deb --build deb dist/hitsz-connect-verge-preview-${{ matrix.os_name }}-${{ matrix.arch }}.deb

    # Upload artifacts common step
    - name: Archive Executable
      uses: actions/upload-artifact@v4
      with:
        name: hitsz-connect-verge-preview-${{ matrix.os_name }}-${{ matrix.arch }}
        path: |
          ${{ runner.os == 'macOS' && 'dist/hitsz-connect-verge-preview-*.dmg' || '' }}
          ${{ runner.os == 'Windows' && 'dist/hitsz-connect-verge-preview-*-setup.exe' || '' }}
          ${{ runner.os == 'Linux' && 'dist/hitsz-connect-verge-preview-*.deb' || '' }}
        if-no-files-found: error
